-- Fix 1: Recreate trust_center_public_data view as SECURITY INVOKER
-- This ensures the view uses the querying user's permissions instead of the view creator's

DROP VIEW IF EXISTS public.trust_center_public_data;

CREATE OR REPLACE VIEW public.trust_center_public_data 
WITH (security_invoker = true)
AS
SELECT 
    company_slug,
    custom_domain,
    logo_url,
    primary_color,
    custom_message,
    seo_title,
    seo_description,
    show_score,
    show_frameworks,
    show_controls,
    show_last_audit,
    CASE
        WHEN show_score THEN (
            SELECT COALESCE(avg(f.compliance_score), 0::numeric)::integer
            FROM frameworks f
            WHERE f.user_id = s.user_id
        )
        ELSE NULL::integer
    END AS compliance_score,
    CASE
        WHEN show_frameworks THEN (
            SELECT jsonb_agg(jsonb_build_object(
                'name', COALESCE(tf.display_name, f.name),
                'certification_date', tf.certification_date,
                'certificate_url', tf.certificate_url,
                'compliance_score', f.compliance_score,
                'passed_controls', f.passed_controls,
                'total_controls', f.total_controls
            ))
            FROM trust_center_frameworks tf
            JOIN frameworks f ON f.id = tf.framework_id
            WHERE tf.user_id = s.user_id AND tf.show_public = true
        )
        ELSE NULL::jsonb
    END AS public_frameworks,
    CASE
        WHEN show_controls THEN (
            SELECT jsonb_build_object(
                'total', count(*),
                'passing', count(*) FILTER (WHERE c.status = 'implemented'::text),
                'in_progress', count(*) FILTER (WHERE c.status = 'in_progress'::text),
                'not_started', count(*) FILTER (WHERE c.status = 'not_implemented'::text)
            )
            FROM controls c
            WHERE c.user_id = s.user_id
        )
        ELSE NULL::jsonb
    END AS controls_summary,
    CASE
        WHEN show_last_audit THEN (
            SELECT jsonb_build_object(
                'framework', a.framework,
                'status', a.status,
                'end_date', a.end_date,
                'auditor', a.auditor
            )
            FROM audits a
            WHERE a.user_id = s.user_id
            ORDER BY a.end_date DESC NULLS LAST
            LIMIT 1
        )
        ELSE NULL::jsonb
    END AS last_audit,
    updated_at AS last_updated
FROM trust_center_settings s
WHERE enabled = true;

-- Grant public access to the view (it's intended for public Trust Center pages)
GRANT SELECT ON public.trust_center_public_data TO anon;
GRANT SELECT ON public.trust_center_public_data TO authenticated;

-- Fix 2: Add token_hash column for secure token storage
-- This allows us to store hashed tokens instead of plaintext

ALTER TABLE public.auditor_access_tokens 
ADD COLUMN IF NOT EXISTS token_hash TEXT;

-- Create index on token_hash for efficient lookups
CREATE INDEX IF NOT EXISTS idx_auditor_tokens_hash 
ON public.auditor_access_tokens(token_hash) 
WHERE is_revoked = false;

-- Revoke existing tokens that only have plaintext (cannot be hashed retroactively)
-- These will need to be regenerated by users
UPDATE public.auditor_access_tokens 
SET is_revoked = true
WHERE token_hash IS NULL AND is_revoked = false;

-- Add comment to document the security improvement
COMMENT ON COLUMN public.auditor_access_tokens.token_hash IS 'SHA-256 hash of the token. The plaintext token is only shown once during creation and never stored.';

-- After migration, we will make the old token column optional (existing apps might still need time to migrate)
-- In a future migration, we can drop the token column entirely
ALTER TABLE public.auditor_access_tokens 
ALTER COLUMN token DROP NOT NULL;