// This file is automatically generated. Do not edit it directly.
// Usa fallbacks e try/catch para evitar tela branca (Lovable/outros hosts sem env).
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const FALLBACK_URL = "https://ofbyxnpprwwuieabwhdo.supabase.co";
const FALLBACK_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9mYnl4bnBwcnd3dWllYWJ3aGRvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc2MDY4NTEsImV4cCI6MjA3MzE4Mjg1MX0.aHH2NWUQZnvV6FALdBIP5SB02YbrE8u12lXI1DtIbiw";

let SUPABASE_URL = FALLBACK_URL;
let SUPABASE_PUBLISHABLE_KEY = FALLBACK_KEY;
try {
  const u = import.meta.env.VITE_SUPABASE_URL;
  const k = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY;
  if (u != null && String(u).trim()) SUPABASE_URL = String(u).trim();
  if (k != null && String(k).trim()) SUPABASE_PUBLISHABLE_KEY = String(k).trim();
} catch (_) {
  // mantém fallbacks se env não existir
}

function createSupabaseClient(): ReturnType<typeof createClient<Database>> {
  try {
    return createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
      auth: {
        storage: typeof localStorage !== 'undefined' ? localStorage : undefined,
        persistSession: true,
        autoRefreshToken: true,
      },
    });
  } catch (e) {
    console.error('[Supabase] createClient failed, retrying without options:', e);
    try {
      return createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);
    } catch (e2) {
      console.error('[Supabase] createClient failed again:', e2);
      throw e2;
    }
  }
}

export const supabase = createSupabaseClient();
